### ISSUE TITLE
该程序有后门，别下载

### ISSUE THREAD

**Issue by 347288629** [lizhipay/mcy-shop#11]
有后门！别下载后门文件为mcy-shop-main/index/kernel/Plugin/Store.php我发现了该程序把ssh公钥写进了我的服务器，并且在偷偷的跑流量，如果下载了建议重装系统！

**Comment by lizhipay** [comment]
程序本身未包含任何后门代码。`Store.php` 文件是应用商店的核心组件，若您需要进行二次开发，可以选择删除此文件。请注意，删除后将无法下载、安装应用商店插件以及使用相关功能，但不会对程序主体功能造成任何影响。

The program does not contain any backdoors. The `Store.php` file serves as the core component of the application store. If you intend to perform secondary development, you may choose to delete this file. Please note that once deleted, downloading, installing, and utilizing application store plugins will no longer be possible. However, this will not affect the core functionality of the program.

**Comment by 347288629** [comment]
删除之和整个程序都无法运行了，目前大量文件引入了这个文件
