### ISSUE TITLE
建议在支付页面二维码上方标注应付总金额

### ISSUE THREAD

**Issue by zyk121381** [lizhipay/mcy-shop#2]
当开启手续费时，若采用码支付接口微信/支付宝等需要客户自己输入金额时，手机端上客户需要下划页面才能看到应付总额。为防止客户没有付回调所需要的金额，建议在付款二维码正上方或下方添加总金额。

自己修改代码时，页面中无法显示修改代码的参数

**Comment by lizhipay** [comment]
there is no such problem at present. If you obtain the QR code through MAPI, you can see all the sending fees through the page rendered locally by our system.
