### ISSUE TITLE
内部收银台功能支付宝无法使用登录账号付款

### ISSUE THREAD

**Issue by xzjue5** [lizhipay/mcy-shop#4]
更新5.0.17后用支付宝的时候只能扫码，点登录账号付款没有反应
![微信截图_20241023001139](https://github.com/user-attachments/assets/8d6e439d-71a3-48f9-9371-ead8a1cdc76d)

**Comment by lizhipay** [comment]
the issue has been received, please wait for it to be fixed.

**Comment by xzjue5** [comment]
这个大概什么时候可以修复
